#!/bin/sh

# Use Bertie's secret folder full of feels if possible.
# Ensure anyone else checking out this project get's one vanilla feel
# for the full but emotionally severly limited experience.
VID_SRC=~/Amazon\ Drive/internet\ gold/Bertie\ Bott\'s\ Every\ Flavour\ Feels
if [ ! -d "$VID_SRC" ]; then
  VID_SRC=vid
fi

rsync -rPh package.json yarn.lock script dist root@51.15.63.110:~/eff/
rsync -rPh "$VID_SRC"/*.webm root@51.15.63.110:~/eff/dist/public/vid/
