#!/bin/sh
rsync -rPh package.json yarn.lock script dist root@51.15.63.110:~/eff/
rsync -rPh ~/Amazon\ Drive/internet\ gold/Bertie\ Bott\'s\ Every\ Flavour\ Feels/*.webm root@51.15.63.110:~/eff/dist/public/vid/
